### ISSUE TITLE
asgardeo_auth.exception.asgardeo_auth_error.AsgardeoAuthError: Initialized OpenID Provider configuration from default configuration. Because failed to access wellknown endpoint: https://localhost:9443/t/wso2.com/oauth2/token/.well-know n/openid-configuration

### ISSUE THREAD

**Issue by faizanshah512** [asgardeo/asgardeo-auth-python-sdk#29]
asgardeo_auth.exception.asgardeo_auth_error.AsgardeoAuthError: Initialized OpenID Provider configuration from default configuration. Because failed to access wellknown endpoint: https://localhost:9443/t/wso2.com/oauth2/token/.well-know
n/openid-configuration

i face this error

**Comment by tejaswinipratappatil** [comment]
same issue I am also facing. could you please let us know whats wrong with the configuration?

**Comment by akuardit** [comment]
same error on me, using wso2 docker.

has change to 
https://localhost:9443/oauth2/token/.well-known/openid-configuration

but still, got the same error
asgardeo_auth.exception.asgardeo_auth_error.AsgardeoAuthError: Initialized OpenID Provider configuration from default configuration. Because failed to access wellknown endpoint: https://localhost:9443/oauth2/token/.well-known/openid-configuration

**Comment by faizanshah512** [comment]
i slove this

**Comment by faizanshah512** [comment]
go to /sample/flask/config.py
"certificate_path": False
set the False property ->certificate_path:False
or provide a valid wso2 certificate

**Comment by thivi** [comment]
Resolved by https://github.com/asgardeo/asgardeo-auth-python-sdk/pull/31
